Module Digests

    Public Const iBSS___1_0___PartialDigest = ""
    Public Const iBSS___1_0_1___PartialDigest = ""
    Public Const iBSS___1_0_2___PartialDigest = ""
    Public Const iBSS___1_1___PartialDigest = ""
    Public Const iBSS___1_1_1___PartialDigest = ""
    Public Const iBSS___1_1_2___PartialDigest = ""
    Public Const iBSS___1_1_3___PartialDigest = ""
    Public Const iBSS___1_1_4___PartialDigest = ""
    Public Const iBSS___1_1_5___PartialDigest = ""

    Public Const iBSS___2_0___PartialDigest = ""
    Public Const iBSS___2_0_1___PartialDigest = ""
    Public Const iBSS___2_0_2___PartialDigest = ""
    Public Const iBSS___2_1___PartialDigest = ""
    Public Const iBSS___2_2___PartialDigest = ""
    Public Const iBSS___2_2_1___PartialDigest = ""

    Public Const iBSS___3_0___PartialDigest = ""
    Public Const iBSS___3_0_1___PartialDigest = ""
    Public Const iBSS___3_1___PartialDigest = ""
    Public Const iBSS___3_1_2___PartialDigest = ""
    Public Const iBSS___3_1_3___PartialDigest = ""
    Public Const iBSS___3_2___PartialDigest = ""
    Public Const iBSS___3_2_1___PartialDigest = ""
    Public Const iBSS___3_2_2___PartialDigest = ""

    Public Const iBSS___4_0___PartialDigest = ""
    Public Const iBSS___4_0_1___PartialDigest = ""
    Public Const iBSS___4_0_2___PartialDigest = ""
    Public Const iBSS___4_1___PartialDigest = "QAAAADhRAgDSCg75CQG2oLHyQCWZq14dcd2j0g=="
    'Public Const iBSS___4_2___PartialDigest = ""
    Public Const iBSS___4_2_1___PartialDigest = "QAAAADhRAgBSoScLOZ7e8n7DQ+oIBonZxvNi8A=="
    Public Const iBSS___4_2_5___PartialDigest = ""
    Public Const iBSS___4_2_6___PartialDigest = ""
    Public Const iBSS___4_2_7___PartialDigest = ""
    Public Const iBSS___4_2_8___PartialDigest = ""
    Public Const iBSS___4_2_9___PartialDigest = ""
    Public Const iBSS___4_2_10___PartialDigest = ""
    Public Const iBSS___4_3___PartialDigest = "QAAAADhhAgC6MB9Qc3zNypWkMYRQ3JWY23YSTA=="
    Public Const iBSS___4_3_1___PartialDigest = "QAAAADhhAgAFQKiaAfLBjvXJy7uRm3gWrbZJTg=="
    Public Const iBSS___4_3_2___PartialDigest = ""
    Public Const iBSS___4_3_3___PartialDigest = "QAAAADhhAgCKiZyqZFFYRdCNwl60rmAZhQfmUg=="
    Public Const iBSS___4_3_4___PartialDigest = "QAAAADhhAgCPraPsV9WaSr8sUbTvOCqAnm003A=="
    Public Const iBSS___4_3_5___PartialDigest = "QAAAADhhAgCPraPsV9WaSr8sUbTvOCqAnm003A=="

    Public Const iBSS___5_0___PartialDigest = "QAAAALgBAQCwDiaxAC8GC/QAPdd53HJHKu3bbQ=="
    Public Const iBSS___5_0_1___PartialDigest = "QAAAALgBAQBshzNlrkauBQ6MJdfDazH7Jl8j4A=="
    Public Const iBSS___5_1___PartialDigest = "QAAAALgBAQAr4vErdNGiRJWy+q9kmbRQc4x9Zw=="
    Public Const iBSS___5_1_1___9B206___PartialDigest = "QAAAALjxAACWl44oOHoA7JpsJZaYXUz9O3EIjA=="
    Public Const iBSS___5_1_1___9B208___PartialDigest = "QAAAALjBAwCUy+Qf9LmhMO3HFmsbXvmHYjyDJw=="

    Public Const iBSS___6_0___PartialDigest = "QAAAAHgBAQCUgQ9mzvkSrqz9uCyrkNV9BpG57g=="
    Public Const iBSS___6_0_1___PartialDigest = "QAAAAHghAQAQ1ufaMjHdOADBgg3d5ZpTKVeuhA=="
    Public Const iBSS___6_0_2___PartialDigest = "QAAAAHghAQAOa9byF0SMd/W5m2U9VUJA3/lykw=="
    Public Const iBSS___6_1___PartialDigest = "QAAAAHgBAQDJeFenIfQe1QZcnJjgtvvK2yTGMg=="
    Public Const iBSS___6_1_1___PartialDigest = "QAAAAHghAQC0dKrsKk1g5b9HVTPsjdpZW0Tciw=="
    Public Const iBSS___6_1_2___PartialDigest = "QAAAAHgBAQAiqCAgqvPxtBf/GP6QmuqSXKXj8g=="
    Public Const iBSS___6_1_3___PartialDigest = "QAAAAHgBAQDb2ZxzNSEasr9l2grgkfWjpYLsNA=="
    Public Const iBSS___6_1_4___PartialDigest = "QAAAAHghAQAQGNgsvY1lcEXslWnbrEZXhtnFJA=="
    Public Const iBSS___6_1_5___PartialDigest = "QAAAAHgBAQAt5oIoOpoJcT5PjUBRn9kruDA5dw=="
    Public Const iBSS___6_1_6___PartialDigest = "QAAAAHgBAQAt5oIoOpoJcT5PjUBRn9kruDA5dw=="

    Public Const iBSS___7_0___PartialDigest = "QAAAAHgBAQBXg+ZEZllrEP6bW/ybwTgnjlKOSA=="
    Public Const iBSS___7_0_1___PartialDigest = "QAAAAHghAQAG2/C4YE5s3DwXR7HxGyyiTobP3A=="
    Public Const iBSS___7_0_2___PartialDigest = "QAAAAHgBAQDEcQ5vQtT81T1U5fUqwN6oOuvHoQ=="
    Public Const iBSS___7_0_3___PartialDigest = "QAAAAHgBAQBYDcSYSPIRkdwon7shgN4s0+EeaA=="
    Public Const iBSS___7_0_4___PartialDigest = "QAAAAHgBAQA8oNxEr0DUxJTsKtjOpzb6x/I0Uw=="
    Public Const iBSS___7_0_5___PartialDigest = "QAAAAHghAQBGwr2ujms8x21UNJAPsLpoCWqd3g=="
    Public Const iBSS___7_0_6___PartialDigest = "QAAAAHgBAQBFMAFYYRGXzg60zn5z+CFKIi/MVA=="
    Public Const iBSS___7_1___PartialDigest = "QAAAAHgBAQDyU+jtpmW9IfiEBTa/W0o2gbEeFw=="
    Public Const iBSS___7_1_1___PartialDigest = "QAAAAHgBAQCQigkQElrA8O141WZk3eP8ugvS5A=="
    Public Const iBSS___7_1_2___PartialDigest = "QAAAAHghAQDD1pyShetVOsoeobYLu4IwnInCSg=="

    Public Const iBSS___8_0___PartialDigest = "QAAAAHgxAQCE5maDJ0amB51JF4ggDwBwIktsdg=="
    Public Const iBSS___8_0_1___PartialDigest = "QAAAAHghAQDWw4nXWZd9n0ZIc6jbYQjFfHWouw=="
    Public Const iBSS___8_0_2___PartialDigest = "QAAAAHghAQDWw4nXWZd9n0ZIc6jbYQjFfHWouw=="
    Public Const iBSS___8_1___PartialDigest = "QAAAAHghAQDMClArp0mXkD0kRyCqhiSSy0vkxQ=="
    Public Const iBSS___8_1_1___PartialDigest = "QAAAAHghAQDL9KRXmhBq8IYpzNngnaXaepMKaw=="
    Public Const iBSS___8_1_2___PartialDigest = "QAAAAHghAQDL9KRXmhBq8IYpzNngnaXaepMKaw=="
    Public Const iBSS___8_1_3___PartialDigest = "QAAAAHghAQCVwdN0Us6rm2ef6/d99VTGndXWrg=="
    Public Const iBSS___8_2___PartialDigest = "QAAAAHgxAQAEdyU7TMmw2TGwpOMtpGwCqxmZTw=="
    Public Const iBSS___8_3___PartialDigest = "QAAAAHghAQDqhTpeHszxtrcrvePvta/SlQYtpw=="
    Public Const iBSS___8_4___PartialDigest = "QAAAAHgxAQD6jlljn7/cZUG16VZSaaOHZZRptg=="
    Public Const iBSS___8_4_1___PartialDigest = ""

    Public Const iBSS___9_0___PartialDigest = ""

End Module
